#!/usr/bin/env bash
# scripts/check-structure.sh

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../src" && pwd)"
OUTPUT_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/STRUCTURE.md"

indent() {
  local level=$1
  for ((i = 0; i < level; i++)); do
    printf "  "
  done
}

# เก็บไฟล์ .ts, .tsx ทั้งหมดแบบ relative path
mapfile -t entries < <(find "$ROOT_DIR" -type f \( -name "*.ts" -o -name "*.tsx" \) | sed "s|^$ROOT_DIR/||" | sort)

declare -A seen
output=""

for entry in "${entries[@]}"; do
  IFS='/' read -ra parts <<< "$entry"
  current=""
  for i in "${!parts[@]}"; do
    current+="${parts[i]}"
    key="${i}-${current}"

    if [[ -z "${seen[$key]}" ]]; then
      seen["$key"]=1

      # เช็คว่าชิ้นนี้คือไฟล์หรือโฟลเดอร์ (ไฟล์จะอยู่ตำแหน่งสุดท้าย และมี dot)
      if [[ $i -eq $((${#parts[@]} - 1)) && "${parts[i]}" == *.* ]]; then
        # ไฟล์ ไม่ต้องขึ้นบรรทัด / ต่อ
        output+=$(indent "$i")"- ${parts[i]}"$'\n'
      else
        # โฟลเดอร์ ใส่ / ต่อท้าย
        output+=$(indent "$i")"- ${parts[i]}/"$'\n'
      fi
    fi
    current+="/"
  done
done

{
  echo "# 📁 Project Source Structure (\`src/\`)"
  echo
  echo '```text'
  echo "$output"
  echo '```'
  echo
  echo '> ✅ Generated by `scripts/check-structure.sh`'
  echo '> ℹ️ NOTE: โค้ดทั้งหมดทำงานภายใต้แนวทาง Dev to Dev แบบเข้มงวด ตรวจสอบโครงสร้างโปรเจกต์ให้เป็นระบบ หลีกเลี่ยงการแตกไฟล์นอกคำสั่งหรือ generate ที่ไม่คำสั่ง                                                  ข้อมูล Dependencies และ DevDependencies (Project)

Dependencies (ไลบรารีหลักที่ใช้ในโปรเจกต์)

@faker-js/faker v9.9.0 — สร้างข้อมูลปลอมสำหรับทดสอบ

@headlessui/react v2.2.7 — UI components แบบไร้สไตล์

@heroicons/react v2.2.0 — ไอคอนจาก Heroicons สำหรับ React

@radix-ui/react-slot v1.2.3 — Slot primitive สำหรับ React component composition

axios v1.11.0 — HTTP client

bcryptjs v3.0.2 — การเข้ารหัสรหัสผ่านแบบ JavaScript

clsx v2.1.1 — จัดการ className conditionally

crypto-browserify v3.12.1 — รองรับ Crypto API ใน browser

framer-motion v12.23.12 — Animation library สำหรับ React

html2canvas v1.4.1 — แปลง DOM เป็น canvas

jspdf v3.0.1 — สร้างไฟล์ PDF

lucide-react v0.537.0 — ชุดไอคอนสำหรับ React

react v19.1.1 — React framework หลัก

react-dom v19.1.1 — DOM rendering สำหรับ React

react-hook-form v7.62.0 — การจัดการฟอร์มใน React

react-icons v5.5.0 — ชุดไอคอนสำหรับ React

react-qr-code v2.0.18 — สร้าง QR code ใน React

react-router-dom v7.8.0 — การจัดการ routing

tailwind-merge v3.3.1 — รวม class ของ Tailwind CSS โดยอัตโนมัติ

zod v4.0.15 — การ validate schema สำหรับ data



---

DevDependencies (เครื่องมือสำหรับพัฒนาและ build)

@eslint/js v9.32.0 — ESLint core สำหรับ JavaScript

@tailwindcss/aspect-ratio v0.4.2 — Plugin Tailwind สำหรับจัดการอัตราส่วน

@tailwindcss/forms v0.5.10 — Plugin Tailwind สำหรับฟอร์ม

@tailwindcss/line-clamp v0.4.4 — Plugin Tailwind สำหรับตัดข้อความ

@tailwindcss/postcss v4.1.11 — Tailwind plugin สำหรับ PostCSS (รุ่นใหม่ของ Tailwind 4.x)

@tailwindcss/typography v0.5.16 — Plugin Tailwind สำหรับจัดการ Typography

@types/node v24.2.0 — TypeScript types สำหรับ Node.js

@types/react v19.1.9 — TypeScript types สำหรับ React

@types/react-dom v19.1.7 — TypeScript types สำหรับ ReactDOM

@typescript-eslint/eslint-plugin v8.39.0 — ESLint plugin สำหรับ TypeScript

@typescript-eslint/parser v8.39.0 — ตัว parser ESLint สำหรับ TypeScript

@vitejs/plugin-react v5.0.0 — Vite plugin สำหรับ React

autoprefixer v10.4.21 — เพิ่ม vendor prefixes อัตโนมัติใน CSS

daisyui v5.0.50 — UI component library บน Tailwind

eslint v9.32.0 — เครื่องมือวิเคราะห์โค้ด JavaScript

eslint-config-prettier v10.1.8 — ปิดการตั้งค่าที่ขัดแย้งกับ Prettier

eslint-plugin-prettier v5.5.4 — รวม Prettier เข้ากับ ESLint

eslint-plugin-react v7.37.5 — ESLint rules สำหรับ React

eslint-plugin-react-hooks v5.2.0 — ESLint rules สำหรับ React Hooks

eslint-plugin-react-refresh v0.4.20 — Hot reload สำหรับ React

globals v16.3.0 — ประกาศ global variables

husky v9.1.7 — Git hooks

lint-staged v16.1.4 — รัน linter บน staged files

postcss v8.5.6 — CSS processor

prettier v3.6.2 — Format code อัตโนมัติ

tailwindcss v3.3.2 (อัปเกรดเป็น 4.1.11 ได้) — CSS utility framework

ts-node v10.9.2 — รัน TypeScript ใน Node.js

tsconfig-paths v4.2.0 — รองรับ path mapping ใน tsconfig

typescript v5.9.2 — ภาษา TypeScript

typescript-eslint v8.39.0 — เครื่องมือรวม ESLint กับ TypeScript

vite v7.1.0 — Build tool สำหรับ frontend

vite-tsconfig-paths v5.1.4 — plugin Vite รองรับ tsconfig path alias



---

เทคนิคและ Best Practices ในการจัดการ Dependencies & เขียนโค้ด

1. เวอร์ชันล็อกให้ชัดเจน
กำหนดเวอร์ชันที่เหมาะสม (เช่น 3.3.2 แทน latest) เพื่อลดปัญหาจากการอัปเดตอัตโนมัติที่อาจทำให้โค้ดไม่ทำงาน


2. แยก dependencies กับ devDependencies ให้ชัดเจน

dependencies สำหรับโค้ดที่รันจริงบนโปรดักชัน

devDependencies สำหรับเครื่องมือพัฒนา เช่น linter, build tools



3. อัปเดต dependency อย่างสม่ำเสมอ
แต่ให้ทดสอบก่อนว่าการอัปเดตเวอร์ชันใหม่ไม่ทำให้ระบบเสียหาย


4. ใช้เครื่องมือจัดการเวอร์ชัน
เช่น pnpm ที่เร็วและประหยัดพื้นที่กว่า npm/yarn


5. ตั้งค่า ESLint + Prettier ร่วมกัน
เพื่อความสม่ำเสมอและลดข้อผิดพลาดเชิงไวยากรณ์ในโค้ด


6. ใช้ TailwindCSS plugin แยกให้ถูกต้อง
Tailwind 4.x แยก plugin postcss ออกมา ต้องเพิ่ม @tailwindcss/postcss เพื่อไม่ให้เกิด error


7. ใช้ alias path ใน TypeScript และ Vite
ลดการเขียน path ยาวๆ ช่วยให้โค้ดดูสะอาดและง่ายต่อการ refactor


8. ตั้งค่า husky + lint-staged
เพื่อรัน linter ก่อน commit ป้องกันโค้ดไม่ดีเข้าสู่ repo


9. ใช้ Vite เพื่อ build
เน้นความเร็วในการพัฒนาและ build


10. แยก theme และ styling ออกจาก logic
เช่นใช้ daisyUI + TailwindCSS ช่วยแยกหน้าที่ชัดเจนและง่ายต่อการปรับธีม
'
} > "$OUTPUT_FILE"

echo "✅ STRUCTURE.md generated at: $OUTPUT_FILE"