#!/usr/bin/env bash
# scripts/check-structure.sh

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../src" && pwd)"
OUTPUT_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/STRUCTURE.md"

indent() {
  local level=$1
  for ((i = 0; i < level; i++)); do
    printf "  "
  done
}

# เก็บไฟล์ .ts, .tsx ทั้งหมดแบบ relative path
mapfile -t entries < <(find "$ROOT_DIR" -type f \( -name "*.ts" -o -name "*.tsx" \) | sed "s|^$ROOT_DIR/||" | sort)

declare -A seen
output=""

for entry in "${entries[@]}"; do
  IFS='/' read -ra parts <<< "$entry"
  current=""
  for i in "${!parts[@]}"; do
    current+="${parts[i]}"
    key="${i}-${current}"

    if [[ -z "${seen[$key]}" ]]; then
      seen["$key"]=1

      # เช็คว่าชิ้นนี้คือไฟล์หรือโฟลเดอร์ (ไฟล์จะอยู่ตำแหน่งสุดท้าย และมี dot)
      if [[ $i -eq $((${#parts[@]} - 1)) && "${parts[i]}" == *.* ]]; then
        # ไฟล์ ไม่ต้องขึ้นบรรทัด / ต่อ
        output+=$(indent "$i")"- ${parts[i]}"$'\n'
      else
        # โฟลเดอร์ ใส่ / ต่อท้าย
        output+=$(indent "$i")"- ${parts[i]}/"$'\n'
      fi
    fi
    current+="/"
  done
done

{
  echo "# 📁 Project Source Structure (\`src/\`)"
  echo
  echo '```text'
  echo "$output"
  echo '```'
  echo
  echo '> ✅ Generated by `scripts/check-structure.sh`'
  echo '> ℹ️ NOTE: โค้ดทั้งหมดทำงานภายใต้แนวทาง Dev to Dev แบบเข้มงวด ตรวจสอบโครงสร้างโปรเจกต์ให้เป็นระบบ หลีกเลี่ยงการแตกไฟล์นอกคำสั่งหรือ generate ที่ไม่คำสั่ง    นี่คือรายละเอียดเว็บไซต์ของเรา  กำหนดให้ AI CHAT GPT เป็นนักออกแบบเว็บไซต์ และเขียน Code ระดับ Professional ตอบสนองดีทั้งบนมือถือและเดสทอปรา

# 📦 โปรเจกต์ vite-react@1.0.0

**สภาพแวดล้อม:** Termux (Android)  
**เทคโนโลยีหลัก:** React 18.3.1 + Vite 7.1.2 + TypeScript 5.9.2 + TailwindCSS 3.3.2 + DaisyUI 5.0.50  

---

## 🚀 ขั้นตอนการทำงาน (Command Logs)

### 1. Development Server
```bash
#pnpm dev

VITE v7.1.2 พร้อมใช้งานใน 1021 ms

Local: http://localhost:5173/

DaisyUI 5.0.50 โหลดสำเร็จ



---

2. Build Production

#pnpm build

ขั้นตอน:

1. tsc -b ตรวจสอบ TypeScript


2. vite build (2928 modules transformed)



ผลลัพธ์ไฟล์:


ไฟล์	ขนาด	Gzip

dist/index.html	2.48 kB	1.00 kB
dist/assets/logo-CH0zBIqT.webp	49.41 kB	-
dist/assets/index-BaarShm4.css	421.56 kB	66.57 kB
dist/assets/403-B81EC2Hb.js	0.61 kB	0.40 kB
dist/assets/SupportFAQ-zd6UzOBV.js	1.49 kB	0.73 kB
dist/assets/PortfolioGallery-YmAVH_4R.js	4.18 kB	1.86 kB
dist/assets/RegistrationPreview-C-U4igXZ.js	4.38 kB	1.77 kB
dist/assets/SalaryCertificate-DUnIp6aq.js	4.55 kB	1.67 kB
dist/assets/CustomerAssessmentForm-Cc_z3d8r.js	5.88 kB	1.96 kB
dist/assets/Login-DBoKZjwV.js	6.07 kB	2.86 kB
dist/assets/SecretPage-CLNYdE8d.js	16.42 kB	6.01 kB
dist/assets/index-yZesCfvL.js	17.78 kB	5.96 kB
dist/assets/Home-fSkx8qms.js	37.15 kB	9.54 kB
dist/assets/vendor_react-Zukt7HCs.js	330.34 kB	109.51 kB
dist/assets/vendor_misc-Cw-csIIc.js	846.74 kB	264.37 kB


⏱️ เวลารวม: 37.86s


---

3. Preview Production

#pnpm preview

Local: http://localhost:4173/



---

4. ตรวจสอบ TypeScript

#pnpm type-check

tsc --noEmit ผ่าน ไม่มี error



---

5. ตรวจสอบ Lint

pnpm lint

ESLint 9.33.0 + Prettier 3.6.2



---

📚 Dependencies

Main:

@faker-js/faker 9.9.0
@headlessui/react 2.2.7
@heroicons/react 2.2.0
@radix-ui/react-slot 1.2.3
axios 1.11.0
bcryptjs 3.0.2
clsx 2.1.1
crypto-browserify 3.12.1
framer-motion 12.23.12
html2canvas 1.4.1
install 0.13.0
jspdf 3.0.1
lucide-react 0.537.0
react 18.3.1
react-dom 18.3.1
react-hook-form 7.62.0
react-icons 5.5.0
react-qr-code 2.0.18
react-router-dom 7.8.0
tailwind-merge 3.3.1
uuid 11.1.0
zod 4.0.17

Dev:

@eslint/js 9.33.0
@tailwindcss/aspect-ratio 0.4.2
@tailwindcss/forms 0.5.10
@tailwindcss/line-clamp 0.4.4
@tailwindcss/postcss 4.1.11
@tailwindcss/typography 0.5.16
@types/node 24.2.1
@types/react 18.3.23
@types/react-dom 18.3.7
@typescript-eslint/eslint-plugin 8.39.1
@typescript-eslint/parser 8.39.1
@vitejs/plugin-react 5.0.0
autoprefixer 10.4.21
daisyui 5.0.50
esbuild 0.25.8
eslint 9.33.0
eslint-config-prettier 10.1.8
eslint-plugin-prettier 5.5.4
eslint-plugin-react 7.37.5
eslint-plugin-react-hooks 5.2.0
eslint-plugin-react-refresh 0.4.20
globals 16.3.0
husky 8.0.3
lint-staged 16.1.5
postcss 8.5.6
prettier 3.6.2
tailwindcss 3.3.2
ts-node 10.9.2
tsconfig-paths 4.2.0
typescript 5.9.2
typescript-eslint 8.39.0
vite 7.1.2
vite-tsconfig-paths 5.1.4
zip-a-folder 3.1.9

---

🎯 ฐานลูกค้า (Target Audience)

จากข้อความและบริการที่ระบุ ฐานลูกค้าหลักน่าจะเป็นกลุ่มที่ต้องการ “ความเร็ว + ความเนียน + ความลับ” เช่น

1. ผู้ประกอบการธุรกิจนอกระบบ/สีเทา

เช่น ธุรกิจที่ต้องการภาพลักษณ์มืออาชีพเพื่อให้ลูกค้าหรือคู่ค้าเชื่อถือ

เน้นเรื่องความปลอดภัยของข้อมูล



2. ฟรีแลนซ์ / เอเจนซี่ที่รับงานพิเศษ

ต้องการบริการเสริม เช่น เอกสาร สลิป โลโก้ งานออกแบบ



3. บุคคลทั่วไปที่ต้องใช้เอกสารเฉพาะทางด่วน

เช่น ยื่นวีซ่า ยื่นกู้ ปรับภาพลักษณ์



4. กลุ่มที่ต้องการบริการออกแบบและการตลาดครบวงจร

เช่น สร้างแบรนด์ใหม่ หรือรีแบรนด์เพื่อเปลี่ยนภาพลักษณ์





---

🖥 แนวทางหน้าเว็บไซต์ (Structure & UX)

ผมจะแบ่งเป็น โครงสร้าง + แนวทางการนำเสนอ

1. Hero Section (เปิดหน้าเว็บ)

โลโก้ JP + สโลแกน “พร้อมลุยแบบมืออาชีพ เนียนทุกงาน โปรทุกขั้นตอน”

ปุ่ม CTA ชัดเจน: ดูบริการทั้งหมด และ ติดต่อเรา

ใช้ภาพพื้นหลังที่ให้ความรู้สึกมั่นใจ + มืออาชีพ


2. Why Choose Us / จุดขายหลัก

ความลับปลอดภัย ✅

งานไวใน 24 ชม. ✅

พร้อมลุยทุกเคส ✅

ใช้ Icon + คำสั้นๆ เพื่อสร้างความเชื่อมั่น


3. About Us

เนื้อเรื่องของ JP Visual & Docs

เน้นประสบการณ์ 8+ ปี

เน้นคำว่า “ทีมเบื้องหลังมืออาชีพ”

ใส่ภาพทีมงานแบบ Blurred เพื่อรักษาความลับ


4. Services (บริการของเรา)

แสดงเป็นการ์ด/ไอคอนพร้อมราคา

ปุ่ม CTA: สนใจบริการ → ไปที่ฟอร์มติดต่อ

จัดหมวดหมู่ เช่น:

📄 เอกสาร

🎨 งานออกแบบ

📈 การตลาด

🛠 บริการพิเศษ



5. Portfolio (ผลงานที่ผ่านมา)

ใช้ Grid รูปภาพ + ปุ่ม ดูเพิ่มเติม

เลือกเฉพาะงานที่สามารถเปิดเผยได้


6. FAQ (คำถามที่พบบ่อย)

คำถามเรื่องความถูกต้องตามกฎหมาย

เงื่อนไขการใช้งาน

ขั้นตอนการสั่งงาน


7. Contact

LINE ID, Email, Messenger

ปุ่ม “แชทเลย” ที่เด้งไป LINE/Messenger



---

💡 เพิ่มลูกเล่น

ใส่ระบบ “Request Access” สำหรับบอร์ดข้อมูลพิเศษ (ใช้รหัส)

Testimonials ปลอมชื่อแต่เน้นความน่าเชื่อถือ

เคลม “ความลับของลูกค้าเป็นกฎข้อแรก” ชัดเจนทุกหน้า



'
} > "$OUTPUT_FILE"

echo "✅ STRUCTURE.md generated at: $OUTPUT_FILE"