#!/usr/bin/env bash

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../src" && pwd)"
OUTPUT_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/STRUCTURE.md"

indent() {
  local level=$1
  for ((i = 0; i < level; i++)); do
    printf "  "
  done
}

# เก็บไฟล์ .ts, .tsx ทั้งหมดแบบ relative path
mapfile -t entries < <(find "$ROOT_DIR" -type f \( -name "*.ts" -o -name "*.tsx" \) | sed "s|^$ROOT_DIR/||" | sort)

declare -A seen
output=""

for entry in "${entries[@]}"; do
  IFS='/' read -ra parts <<< "$entry"
  current=""
  for i in "${!parts[@]}"; do
    current+="${parts[i]}"
    key="${i}-${current}"

    if [[ -z "${seen[$key]}" ]]; then
      seen["$key"]=1

      # เช็คว่าชิ้นนี้คือไฟล์หรือโฟลเดอร์ (ไฟล์จะอยู่ตำแหน่งสุดท้าย และมี dot)
      if [[ $i -eq $((${#parts[@]} - 1)) && "${parts[i]}" == *.* ]]; then
        # ไฟล์ ไม่ต้องขึ้นบรรทัด / ต่อ
        output+=$(indent "$i")"- ${parts[i]}"$'\n'
      else
        # โฟลเดอร์ ใส่ / ต่อท้าย
        output+=$(indent "$i")"- ${parts[i]}/"$'\n'
      fi
    fi
    current+="/"
  done
done

cat > "$OUTPUT_FILE" << EOF
# 📁 Project Source Structure (\`src/\`)

\`\`\`text
$output
\`\`\`

> ✅ Generated by \`scripts/check-structure.sh\`

> ℹ️ **NOTE: Dependencies list:**
>
> - @faker-js/faker 9.9.0
> - @headlessui/react 2.2.7
> - @heroicons/react 2.2.0
> - @radix-ui/react-slot 1.2.3
> - axios 1.11.0
> - bcryptjs 3.0.2
> - clsx 2.1.1
> - dayjs 1.11.13
> - framer-motion 12.23.12
> - lucide-react 0.536.0 (0.537.0 is available)
> - react 18.3.1 (19.1.1 is available)
> - react-dom 18.3.1 (19.1.1 is available)
> - react-hook-form 7.62.0
> - react-icons 5.5.0
> - react-qr-code 2.0.18
> - react-router-dom 7.7.1
> - tailwind-merge 3.3.1
> - zod 4.0.15
>
> **DevDependencies:**
>
> - @eslint/js 9.32.0
> - @tailwindcss/aspect-ratio 0.4.2
> - @tailwindcss/forms 0.5.10
> - @tailwindcss/line-clamp 0.4.4
> - @tailwindcss/typography 0.5.16
> - @types/bcryptjs 3.0.0 deprecated
> - @types/node 20.19.9 (24.2.0 is available)
> - @types/react 18.3.23 (19.1.9 is available)
> - @types/react-dom 18.3.7 (19.1.7 is available)
> - @types/react-router-dom 5.3.3
> - @typescript-eslint/eslint-plugin 8.39.0
> - @typescript-eslint/parser 8.39.0
> - @vitejs/plugin-react 4.7.0 (5.0.0 is available)
> - autoprefixer 10.4.21
> - daisyui 5.0.50
> - eslint 9.32.0
> - eslint-config-prettier 9.1.2 (10.1.8 is available)
> - eslint-plugin-prettier 5.5.4
> - eslint-plugin-react 7.37.5
> - eslint-plugin-react-hooks 5.2.0
> - eslint-plugin-react-refresh 0.4.20
> - globals 16.3.0
> - husky 8.0.3 (9.1.7 is available)
> - lint-staged 13.3.0 (16.1.4 is available)
> - postcss 8.5.6
> - prettier 3.6.2
> - tailwindcss 3.4.17 (4.1.11 is available)
> - ts-node 10.9.2
> - tsconfig-paths 4.2.0
> - ttf2woff2 8.0.0
> - typescript 5.9.2
> - typescript-eslint 8.39.0
> - vite 5.4.19 (7.1.0 is available)
> - vite-tsconfig-paths 5.1.4
>
> ⚠️ **Warning:**
>
> Ignored build scripts: ttf2woff2.
> Run "pnpm approve-builds" to pick which dependencies should be allowed to run scripts.

EOF

echo "✅ STRUCTURE.md generated at: $OUTPUT_FILE"