#!/usr/bin/env bash
# scripts/check-structure.sh

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../src" && pwd)"
OUTPUT_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/STRUCTURE.md"

indent() {
  local level=$1
  for ((i = 0; i < level; i++)); do
    printf "  "
  done
}

# เก็บไฟล์ .ts, .tsx ทั้งหมดแบบ relative path
mapfile -t entries < <(find "$ROOT_DIR" -type f \( -name "*.ts" -o -name "*.tsx" \) | sed "s|^$ROOT_DIR/||" | sort)

declare -A seen
output=""

for entry in "${entries[@]}"; do
  IFS='/' read -ra parts <<< "$entry"
  current=""
  for i in "${!parts[@]}"; do
    current+="${parts[i]}"
    key="${i}-${current}"

    if [[ -z "${seen[$key]}" ]]; then
      seen["$key"]=1

      # เช็คว่าชิ้นนี้คือไฟล์หรือโฟลเดอร์ (ไฟล์จะอยู่ตำแหน่งสุดท้าย และมี dot)
      if [[ $i -eq $((${#parts[@]} - 1)) && "${parts[i]}" == *.* ]]; then
        # ไฟล์ ไม่ต้องขึ้นบรรทัด / ต่อ
        output+=$(indent "$i")"- ${parts[i]}"$'\n'
      else
        # โฟลเดอร์ ใส่ / ต่อท้าย
        output+=$(indent "$i")"- ${parts[i]}/"$'\n'
      fi
    fi
    current+="/"
  done
done

{
  echo "# 📁 Project Source Structure (\`src/\`)"
  echo
  echo '```text'
  echo "$output"
  echo '```'
  echo
  echo '> ✅ Generated by `scripts/check-structure.sh`'
  echo '> ℹ️ NOTE: โค้ดทั้งหมดทำงานภายใต้แนวทาง Dev to Dev แบบเข้มงวด ตรวจสอบโครงสร้างโปรเจกต์ให้เป็นระบบ หลีกเลี่ยงการแตกไฟล์นอกคำสั่งหรือ generate ที่ไม่คำสั่ง    นี่คือรายละเอียดเว็บไซต์ของเรา  กำหนดให้ AI CHAT GPT เป็นนักออกแบบเว็บไซต์ และเขียน Code ระดับ Professional ตอบสนองดีทั้งบนมือถือและเดสทอป
  หาไอเดีย เพิ่ม componets หน้าเว็บไซต์ และหาไอเดีย เพิ่มรายละเอียด



บันทึกข้อความ: รายละเอียดโปรเจกต์ 
📥 pnpm found! Installing dependencies...
Downloading react-icons@5.5.0: 22.22 MB/22.22 MB, done
Packages: +710
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 755, reused 0, downloaded 710, added 710, done
. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 1.9s
dependencies:

@faker-js/faker 9.9.0

@headlessui/react 2.2.7

@heroicons/react 2.2.0

@radix-ui/react-slot 1.2.3

axios 1.11.0

bcryptjs 3.0.2

clsx 2.1.1

crypto-browserify 3.12.1

framer-motion 12.23.12

html2canvas 1.4.1

install 0.13.0

jspdf 3.0.1

lucide-react 0.537.0 (0.539.0 is available)

pnpm 10.14.0

react 18.3.1 (19.1.1 is available)

react-dom 18.3.1 (19.1.1 is available)

react-hook-form 7.62.0

react-icons 5.5.0

react-qr-code 2.0.18

react-router-dom 7.8.1

sweetalert2 11.22.3 (11.22.4 is available)

tailwind-merge 3.3.1

theme-change 2.5.0

tsconfig.json 1.0.11

uuid 11.1.0

zod 4.0.17


devDependencies:

@eslint/js 9.33.0

@tailwindcss/aspect-ratio 0.4.2

@tailwindcss/forms 0.5.10

@tailwindcss/line-clamp 0.4.4

@tailwindcss/typography 0.5.16

@testing-library/jest-dom 6.7.0

@testing-library/react 16.3.0

@testing-library/user-event 14.6.1

@types/jest 30.0.0

@types/node 24.3.0

@types/react 18.3.23 (19.1.10 is available)

@types/react-dom 18.3.7 (19.1.7 is available)

@typescript-eslint/eslint-plugin 8.39.1

@typescript-eslint/parser 8.39.1

@vitejs/plugin-react 5.0.0

autoprefixer 10.4.21

daisyui 3.9.4 (5.0.50 is available)

esbuild 0.25.8 (0.25.9 is available)

eslint 9.33.0

eslint-config-prettier 10.1.8

eslint-plugin-prettier 5.5.4

eslint-plugin-react 7.37.5

eslint-plugin-react-hooks 5.2.0

eslint-plugin-react-refresh 0.4.20

globals 16.3.0

husky 8.0.3 (9.1.7 is available)

lint-staged 16.1.5

postcss 8.5.6

prettier 3.6.2

tailwindcss 3.4.17 (4.1.12 is available)

ts-node 10.9.2

tsconfig-paths 4.2.0

typescript 5.9.2

typescript-eslint 8.39.0 (8.39.1 is available)

vite 7.1.2

vite-tsconfig-paths 5.1.4

vitest 3.2.4

zip-a-folder 3.1.9


Done in 1m 17s using pnpm v10.14.0
🗑️ Removing log files...
✅ Clean completed successfully.


---

🛠️ Dev@JP ~/projectjp ❯ pd

> vite-react@7.1.1 dev /data/data/com.termux/files/home/projectjp
vite



VITE v7.1.2  ready in 1740 ms
➜  Local:   http://localhost:5173/
➜  Network: use --host to expose
➜  press h + enter to show help

╭── 🌼 daisyUI 3.9.4 https://daisyui.com
│
├── 3 themes are enabled. How to add more themes: https://daisyui.com/docs/themes
╰── 💚 Support daisyUI project: https://opencollective.com/daisyui


---

🛠️ Dev@JP ~/projectjp ❯ pb

> vite-react@7.1.1 build /data/data/com.termux/files/home/projectjp
tsc -b && vite build



vite v7.1.2 building for production...
╭── 🌼 daisyUI 3.9.4 https://daisyui.com
│
├── 3 themes are enabled. How to add more themes: https://daisyui.com/docs/themes
╰── ⭐️ Star daisyUI project on GitHub: https://github.com/saadeghi/daisyui

transforming (4) src/styles/fonts.css

╭── 🌼 daisyUI 3.9.4 https://daisyui.com
│
├── 3 themes are enabled. How to add more themes: https://daisyui.com/docs/themes
╰── 💚 Support daisyUI project: https://opencollective.com/daisyui

✓ 3268 modules transformed.

dist/index.html                                   2.79 kB │ gzip:   1.03 kB
dist/assets/SecretPage-6VDldoUo.css               2.88 kB │ gzip:   0.89 kB
dist/assets/index-DBhZAgQV.css                  106.39 kB │ gzip:  16.04 kB
dist/assets/403-CgHziCDS.js                       0.61 kB │ gzip:   0.40 kB
dist/assets/IdCardForm-BKHXvkej.js                2.16 kB │ gzip:   0.79 kB
dist/assets/MedicalCertificate-BeONQfXB.js        2.28 kB │ gzip:   0.79 kB
dist/assets/SalaryCertificate-BZASUtfO.js         3.53 kB │ gzip:   1.28 kB
dist/assets/RegistrationPreview-WBfU-0H3.js       4.06 kB │ gzip:   1.70 kB
dist/assets/PortfolioGallery-Dc8Jw2H1.js          4.51 kB │ gzip:   1.94 kB
dist/assets/SupportFAQ-BBhJj7h9.js                5.96 kB │ gzip:   1.92 kB
dist/assets/Login-S44IIrHM.js                     6.17 kB │ gzip:   2.91 kB
dist/assets/CustomerAssessmentForm-Ct1JCPQG.js    7.33 kB │ gzip:   2.27 kB
dist/assets/index-Bvnvwkr-.js                    19.51 kB │ gzip:   6.53 kB
dist/assets/SecretPage-CWf1f6Dj.js               24.56 kB │ gzip:   8.22 kB
dist/assets/Home-BjnIASvv.js                     66.68 kB │ gzip:  16.46 kB
dist/assets/vendor_react-u5eJe2Lx.js            343.80 kB │ gzip: 113.92 kB
dist/assets/vendor_misc-CIr7XjA7.js             848.17 kB │ gzip: 265.34 kB

✓ built in 33.72s


---

🛠️ Dev@JP ~/projectjp ❯ pnpm lint

> vite-react@7.1.1 lint /data/data/com.termux/files/home/projectjp
eslint .




---

🛠️ Dev@JP ~/projectjp ❯ pnpm type-check

> vite-react@7.1.1 type-check /data/data/com.termux/files/home/projectjp
tsc --noEmit




---

🛠️ Dev@JP ~/projectjp

บันทึกข้อความ: หน้าเว็บไซต์ JP Visual & Docs เวอร์ชันปัจจุบันน

1. ส่วน Header / Hero

โลโก้: JP Visual & Docs
ข้อความนำ (Hero Text):

“พร้อมลุยแบบมืออาชีพ”

“เนียนทุกงาน โปรทุกขั้นตอน”

“JP Visual & Docs ทีมเบื้องหลังมืออาชีพ ช่วยให้คุณดูโปรแบบไวที่สุด”


จุดเด่นแนะนำ:

ความลับปลอดภัย

งานไวใน 24 ชั่วโมง

พร้อมลุยทุกเคส

ประสบการณ์ 8+ ปี

ความพึงพอใจ 98–99%

ส่งทันนัด 99%+

ความลับเป็นกฎข้อแรก


สิ่งที่ควรเพิ่ม:

ปุ่ม Call-to-Action ชัดเจน เช่น “ติดต่อเรา” / “ขอคำปรึกษา”

ภาพประกอบ Hero หรือแอนิเมชันสั้นเพื่อสร้างความน่าสนใจ

Highlight ตัวเลขสถิติด้วยไอคอนหรือกราฟิกเล็ก ๆ เพื่อให้เห็นชัดเจน



---

2. ส่วนเกี่ยวกับเรา (About Us)

ข้อความหลัก:

JP Visual & Docs ยกระดับธุรกิจเฉพาะทางให้มีมาตรฐานระดับมืออาชีพ

รวมทีมตัวจริงที่เชี่ยวชาญงานออกแบบและสร้างภาพลักษณ์ดิจิทัล

เน้นความน่าเชื่อถือและความปลอดภัยแม้ธุรกิจอยู่นอกระบบกฎหมายทั่วไป

ประสบการณ์ในวงการมากกว่า 8 ปี


คำพูดเชิง Branding:

“ผมไม่ใช่คนเก่ง แต่ทีมงานผมเก่งแน่นอน”


สิ่งที่ควรเพิ่ม:

รูปทีมงาน / ภาพเบื้องหลังการทำงาน

Timeline แสดงประสบการณ์ 8 ปี

Icon หรือ Badge แสดงรางวัล/ความน่าเชื่อถือ



---

3. จุดเด่นและความน่าเชื่อถือ

ความโดดเด่นของบริการ:

ความลับปลอดภัย ข้อมูลและเอกสารถูกเก็บเข้มงวด

งานไวใน 24 ชั่วโมง

พร้อมลุยทุกเคส

จัดคิวทันทีหลังยืนยันขอบเขต

อัปเดตสถานะโปร่งใส

ส่งไฟล์ปลอดภัย พร้อมลิงก์หมดอายุ


บริการและระบบที่แนะนำ:

วิเคราะห์และปรับโปรไฟล์ลูกค้า

ดูแลเอกสารครบวงจรสำหรับธนาคาร/สถานทูต

สลิปสมจริง พร้อม QR Code

ระบบหลังบ้านและ AI ดูแลกลุ่มลูกค้า


ความสำเร็จ:

ลูกค้าอนุมัติจริงมากกว่า 4,000 รายทั่วประเทศ

ข้อมูลปลอดภัยตามนโยบายสูงสุด


สิ่งที่ควรเพิ่ม:

Testimonials / Quotes ลูกค้า

Icon หรือ Badge แสดงความสำเร็จ เช่น จำนวนลูกค้า, ประสบการณ์

Case Study แบบสั้นให้เห็นผลลัพธ์



---

4. เหตุผลที่วางใจเรา

ข้อมูลปลอดภัยตามมาตรฐานสากล

ระบบเข้ารหัสและป้องกันเข้าถึงโดยไม่ได้รับอนุญาต

การเข้าถึงชั่วคราว รหัสมีเวลาจำกัด

ล็อกอินด้วยรหัสเฉพาะบุคคล

รองรับผู้ใช้หลายระดับ


สิ่งที่ควรเพิ่ม:

Infographic แสดงขั้นตอนการเข้าถึงข้อมูล

Highlight การเข้ารหัสและมาตรฐานความปลอดภัย



---

5. บริการของเรา

ตัวอย่างบริการและราคา

บริการ	รายละเอียด	ราคา

ที่ปรึกษายื่นกู้สินเชื่อ	วิเคราะห์โปรไฟล์ จัดชุดเอกสาร และยื่นตรงธนาคาร	4,000 – 300,000 บาท
ดูแลเอกสารยื่นวีซ่า	ตรวจสอบและจัดชุดเอกสารให้ตรงตามข้อกำหนด	เริ่มต้น 4,000 บาท
SLIBBANK – สลิปโอนเงิน/รับเงิน	ปรับชื่อ ยอด เวลา โลโก้ ใช้ในโปรไฟล์หรือเอกสารประกอบ	100 บาท/ใบ (10 ใบ 500 บาท)
แก้ไข / สร้างเอกสารเฉพาะทาง	แก้ไข 400 / สร้างใหม่ 600 บาท	-
ผลิตบัตรแข็ง / บัตรอ่อน	พร้อมลายน้ำ QR และความปลอดภัยสูง	เริ่มต้น 4,000 บาท
ออกแบบโลโก้ / แบนเนอร์ / ทีม	รองรับทุกแพลตฟอร์ม	เริ่มต้น 300 บาท
ดูแลการตลาดครบวงจร	วางกลยุทธ์คอนเทนต์ ยิงแอด ติดตั้งระบบตอบแชทอัตโนมัติ	5,000 – 500,000 บาท
ระบบดูแลลูกค้าภายใน	AI Matching, จับคู่ลูกค้า, ดูแลลูกค้าผ่าน LINE/Telegram	เริ่มต้น 4,000 บาท
สร้างหรือปรับภาพลักษณ์	รีแบรนด์ภาพบวก/ลบอย่างมืออาชีพ	เริ่มต้น 5,000 บาท
บริการใหม่กำลังเปิดตัว	Coming Soon	-


สิ่งที่ควรเพิ่ม:

ปุ่ม CTA “สนใจบริการ” ให้ชัดเจนสำหรับแต่ละบริการ

รูปภาพประกอบตัวอย่างงาน / icon แยกประเภทบริการ

Filter / Tabs สำหรับเลือกบริการตามหมวด



---

6. ตัวอย่างผลงาน (Portfolio / Case Study)

Website / Dashboard / Landing Page / Mobile App / Graphic

GovHub Corporate Website

เผยเฉพาะสิ่งส่งมอบที่เปิดเผยได้ โดยซ่อนข้อมูลลูกค้า / Metadata


สิ่งที่ควรเพิ่ม:

Carousel แสดงภาพผลงาน

Badge “Rush / Design / Compliance / Delivery” สำหรับงานเร่งด่วน



---

7. FAQ

ตัวอย่างคำถาม-คำตอบ:

สามารถยื่นกู้โดยไม่ใช้เอกสารจริงได้ไหม? → ขึ้นอยู่กับธนาคารและโปรไฟล์

บริการผิดกฎหมายหรือไม่? → ไม่ปลอมเอกสารราชการ แต่เป็นการเตรียมเอกสารเชิงเทคนิค

ใช้เวลานานแค่ไหน? → ปกติ 3-5 วันทำการ

แก้ไขเอกสารได้ไหม? → ได้ภายในระยะเวลาตกลง

การรับประกันเอกสาร → รับประกันข้อมูลสมบูรณ์ แต่ไม่รับประกันผลอนุมัติ

เอกสารสามารถใช้ยื่นทุกธนาคาร? → ตรวจสอบกับธนาคารเป้าหมายอีกครั้ง

ช่องทางติดต่อ → LINE, Messenger, Email


สิ่งที่ควรเพิ่ม:

Accordion / Collapse UI สำหรับ FAQ เพื่อให้อ่านง่าย

Highlight คำสำคัญ เช่น “ปลอดภัย”, “ไว”, “มืออาชีพ”



---

8. ช่องทางติดต่อ

LINE: @462FQFC / @jpsystem.official

Email: contact@jpsystem.dev

Messenger: @jaopa.zerofour


สิ่งที่ควรเพิ่ม:

ปุ่มลิงก์ social media แบบชัดเจน

ฟอร์มติดต่อเร็ว (Quick Contact Form)

Map / Location (ถ้ามีสำนักงานจริง)



---

9. ข้อเสนอแนะเพิ่มเติมเพื่อหน้าเว็บสมบูรณ์

1. Visual Hierarchy: ใช้สีและไอคอนเน้นจุดสำคัญ เช่น สถิติ, ความปลอดภัย, งานไว


2. Responsive Design: รองรับมือถือ, แท็บเล็ต, Desktop


3. CTA ชัดเจนทุกส่วน: Hero / Service / Contact


4. Trust Signals: Badge, Icon, Testimonials, Case Studies


5. SEO / Metadata: เพิ่ม meta description, keywords, og:image


6. Loading Speed: Optimize ภาพและสคริปต์, ใช้ lazy loading


7. Accessibility: Alt text ภาพ, ARIA roles, contrast color


'
} > "$OUTPUT_FILE"

echo "✅ STRUCTURE.md generated at: $OUTPUT_FILE"