#!/usr/bin/env ts-node

import bcrypt from "bcryptjs";
import { writeFileSync } from "fs";
import { resolve } from "path";

// รายชื่อผู้ใช้และรหัสผ่าน plaintext
const passwords: Record<string, string> = {
  admin2517: "myub2517",
  JPKYETONKEY201: "CODSLOUVPJ301",
  JPKYETONKEY222: "CODSLOUVPJ337",
  JPKYETONKEY233: "CODSLOUVPJ379",
  JPKYETONKEY244: "CODSLOUVPJ305",
  JPKYETONKEY255: "CODSLOUVPJ398",
  JPKYETONKEY266: "CODSLOUVPJ320",
  JPKYETONKEY277: "CODSLOUVPJ341",
  JPKYETONKEY288: "CODSLOUVPJ359",
  JPKYETONKEY299: "CODSLOUVPJ407",
  JPKYETONKEY300: "CODSLOUVPJ399",
  JPusertest01: "Peudhdo5",
};

const saltRounds = 10;

// path ของไฟล์ users.ts
const outputFile = resolve(__dirname, "users.ts");

// ฟังก์ชันสร้าง hash ของรหัสผ่าน
async function generateHashes() {
  const results: Record<string, string> = {};

  for (const [username, plainPassword] of Object.entries(passwords)) {
    try {
      const hash = await bcrypt.hash(plainPassword, saltRounds);
      results[username] = hash;
    } catch (err) {
      console.error(`❌ Failed to hash password for "${username}":`, err);
    }
  }

  // สร้างเนื้อหาไฟล์ users.ts
  const fileContent = `// ⚠️ Auto-generated by generateHashes.ts
export const users = ${JSON.stringify(results, null, 2)};\n`;

  writeFileSync(outputFile, fileContent, { encoding: "utf-8" });

  console.log(`✅ users.ts generated at: ${outputFile}`);
}

// เรียกใช้งาน
generateHashes();
