// src/config/users.ts
// Auto-generated by hashPassword.ts

export interface UserData {
  hash: string;
  role: "admin" | "manager" | "user";
}

export const users: Record<string, UserData> = {
  admin2517: {
    hash: "$2b$10$8eRB4lCRUmU/ku5UZCqVxutmAn/koGKOUj..eqIhjuMiULtBRM9wK",
    role: "admin",
  },
  JPKYETONKEY201: {
    hash: "$2b$10$/USY0iZpZD5utHomP0go..P2U1ZglLKXRUZLArCoFn9DtLhD8dcUu",
    role: "user",
  },
  JPKYETONKEY222: {
    hash: "$2b$10$FJbJr3qwBd/JgUsjl4TyV.so5trISxzTDiSffnwwCLQUmN0lVUM9O",
    role: "user",
  },
  JPKYETONKEY233: {
    hash: "$2b$10$Bo6TF2WON8RyHWYzl99a9ulTog/B9uIfxCJsokOfeGuqOcnb9Rrum",
    role: "user",
  },
  JPKYETONKEY244: {
    hash: "$2b$10$.5p7.y865EA2Wve2KpHoqekA/vKg1HHs38j3lq7gMpTK5oGXJrwDK",
    role: "manager",
  },
  JPKYETONKEY255: {
    hash: "$2b$10$2xxnYCyZPVp0EivFoLXFL.zNWDgjsT4rd3oeuwD.goO.UF7wSzJRe",
    role: "user",
  },
  JPKYETONKEY266: {
    hash: "$2b$10$FXG5tbqjBXmZtpVD3c09Wul5ZaNPidj56Os.V5G/nbWWI5XDkrlwW",
    role: "user",
  },
  JPKYETONKEY277: {
    hash: "$2b$10$OhvFkfxRsUTe3M8FS3e7ZeKAF7YhqwfydqoR8AfryebIgWnidfMzu",
    role: "user",
  },
  JPKYETONKEY288: {
    hash: "$2b$10$I5AKZkvzMVO62NehAT/UcukwHUfd9yyLkM9YzFAfZ1mHTOBDt0Nh.",
    role: "user",
  },
  JPKYETONKEY299: {
    hash: "$2b$10$S7Z/4aBmp7gRAnaO49sssOb5AR2YxRqsD/XcE75Y8XDEiLxRLPmrC",
    role: "user",
  },
  JPKYETONKEY300: {
    hash: "$2b$10$4UhmlSpmXNdcOguwlcz0nORX1vK/vt.6f4rPpVTOLu5TbI6ZuyaCK",
    role: "user",
  },
  JPusertest01: {
    hash: "$2b$10$d/m7fBdee1Oo6cBKtnceee0.DqIx9h/O5zdJaN6/YlSjZ6Eg3Q0Fa",
    role: "user",
  },
};
